# Generated by Django 2.1.5 on 2019-02-10 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Creation date')),
                ('modification_date', models.DateField(default=datetime.date.today, verbose_name='Modification date')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('privacy', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('version', models.CharField(default='0.1.0-alpha', max_length=64, null=True)),
            ],
            options={
                'ordering': ('-creation_date',),
                'abstract': False,
            },
        ),
    ]
